language: ruby
rvm:
- 2.2.5
script: ./bin/test

git:
  depth: 3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: script
  script: bin/deploy
  on:
    branch: master