title: Mime Industries
email: info@mime.co.uk
description: >
  Mime Industries makes products that help kids learn about technology
  The MeArm is a build-it-yourself robotic arm and Mirobot is a WiFi
  drawing robot kit.
url: "http://mime.co.uk"
twitter_username: mimeindustries
github_username:  mimeindustries
markdown: kramdown
paginate: 4
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title/
exclude:
 - Gemfile
 - Gemfile.lock
 - s3_website.yml
 - README.md
 - vendor
 - bin
gems:
 - jekyll-paginate
 - jekyll-assets
assets:
  compress:
    css: false
    js: false
  prefix: "/assets"
  digest: true
  sources:
    - assets/js
    - _assets/js
    - _assets/css
    - _assets/apps